routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.pages.auth.login');
})->name('admin.login');

Route::get('/send-email', function (Request $request) {
    return view('admin.pages.auth.send_email');
})->name('admin.send_email');

Route::get('/inscription', function () {
    return view('admin.pages.auth.register');
})->name('inscription');

Route::get('/confirm', function () {
    return view('admin.pages.auth.confirm');
})->name('confirm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'], 'prefix' => 'accueil'], function () {
   
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('locales', 'LocalisationController')->except(['show']);
    Route::resource('roles', 'RoleController')->except(['show']);
    Route::resource('type-rdvs', 'TypeRdvController')->except(['show']);
    Route::resource('antecedents', 'AntecedentController')->except(['show']);
    Route::resource('type-antecedents', 'TypeAntecedentController')->except(['show']);
    Route::resource('type-doctors', 'TypeDoctorController')->except(['show']);
    Route::resource('type-soins', 'TypeSoinController')->except(['show']);
    Route::resource('type-interventions', 'TypeInterventionController')->except(['show']);
    Route::post('users/password', 'UserController@password')->name('users.password');
    Route::get('users/password', 'UserController@getPassword')->name('users.password');
    Route::get('users/role', 'UserController@role');
    Route::put('users/profile', 'UserController@profile')->name('users.profile.update');
    Route::get('users/profile', 'UserController@getprofile')->name('users.profile');
    Route::get('users/zone/{id}/{role}', 'UserController@getUsersByZone')->name('users.zone');
    Route::get('users/listing/{type}', 'UserController@listing')->name('users.listing');
    Route::delete('users/delete/{id}', 'UserController@delete')->name('users.delete');
    Route::get('users/medical', 'UserController@dossierMedical')->name('users.medical');
    Route::get('users/medical/users/{id}', 'UserController@dossierMedicalBis')->name('users.medical.users'); 
    Route::get('users/nurses/index', 'UserController@nursePatient')->name('users.nurses.index');
    Route::get('users/nurses/create', 'UserController@createPatient')->name('users.nurses.create');
    Route::get('users/doctor/patient', 'UserController@doctorPatient')->name('users.doctor.patient');
    Route::get('users/forfait', 'UserController@userForfait')->name('users.forfait');
    Route::post('users/forfait/store', 'UserController@forfait')->name('users.forfait.store');
    Route::post('users/nurses/store', 'UserController@nurseStore')->name('users.nurses.store');
    Route::get('users/assign/patients', 'UserController@getAssignForm')->name('users.assign');
    Route::get('users/assign/{id}', 'UserController@assignFind')->name('users.assign.find');
    Route::post('users/assign/patients', 'UserController@assignPatientToDoctor')->name('users.assign.store');
    Route::resource('users', 'UserController');
    Route::get('intervention/nurse/', 'RdvController@interventionNonNurse')->name('interventions.nurse');
    Route::get('intervention/doctor/', 'RdvController@doctorInvalidRdv')->name('interventions.doctor');
    Route::get('rdvs/patient', 'RdvController@patientRdv')->name('rdvs.patient');
    Route::get('rdvs/doctor', 'RdvController@doctorRdv')->name('rdvs.doctors');
    Route::get('rdvs/nurse', 'RdvController@nurseRdv')->name('rdvs.nurses');
    Route::get('rdvs/nurse/invalid', 'RdvController@nurseInvalidRdv')->name('rdvs.nurses.invalid');
    Route::get('rdvs/confirm/{id}', 'RdvController@confirm');
    Route::resource('rdvs', 'RdvController');
    Route::get('soins/details/{id}', 'SoinController@details')->name('soins.details');
    Route::resource('soins', 'SoinController');
    Route::get('forfaits/details/{id}', 'ForfaitController@detailsForfait');
    Route::resource('forfaits', 'ForfaitController');
    Route::resource('services', 'ServiceController');

    // Route qui affiche les interventions non effectuées par un medecin
    Route::get('interventions/medecin/{id}', 'InterventionController@interventionsNonEffectueesParMedecin')->name('interventions.medecin');
    // Route qui affiche les interventions non effectuées par l'infirmière
    Route::get('interventions/infirmiere/{id}', 'InterventionController@interventionsNonEffectueesParInfirmiere')->name('interventions.infirmiere');
    // Route qui affiche les rendez-vous pour un patient
    //Route::get('rdvs/patient/{id}', 'RdvController@patientRDV')->name('rdvs.patient');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, HasRoles, HasApiTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'surname', 'password', 'sexe', 'lieuNassance', 'dateNaissance', 'contact', 'profession', 'active', 'situation',
         'forfait_id', 'doctor_id', 'localisation_id', 'activation_token', 'role', 'user_id', 'profile', 'busy', 'email_verified_at',
    ];
    protected $guard_name = 'web';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password','remember_token', 'activation_token'
    ];


    public function forfait()
    {
      return $this->belongsTo('App\Models\Forfait');
    }

    public function type_doctor()
    {
      return $this->belongsTo('App\Models\TypeDoctor');
    }

    public function localisation()
    {
      return $this->belongsTo('App\Models\Localisation');
    }

    public function user()
    {
      return $this->belongsTo('App\Models\User');
    }

    public function interventions()
    {
      return $this->hasMany('App\Models\Intervention');
    }

    public function antecedents()
    {
      return $this->hasMany('App\Models\Antecedent');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use Notifiable, SoftDeletes, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'surname', 'password', 'sexe', 'lieuNassance', 'dateNaissance', 'contact', 'profession', 'active',
         'forfait_id', 'doctor_id', 'localisation_id', 'activation_token', 'role', 'user_id', 'profile'
    ];
    protected $guard_name = 'web';

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        'password','remember_token', 'activation_token'
    ];


    public function forfait()
    {
      return $this->belongsTo('App\Models\Forfait');
    }

    public function type_doctor()
    {
      return $this->belongsTo('App\Models\TypeDoctor');
    }

    public function localisation()
    {
      return $this->belongsTo('App\Models\Localisation');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\TypeDoctor;
use App\Mail\UserMail;
use App\Models\Localisation;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;
use Spatie\Permission\PermissionRegistrar;
use Session;
use Redirect;
/*
use PayPal\Api\Amount;
use PayPal\Api\Details;
use PayPal\Api\Item;
use PayPal\Api\ItemList;
use PayPal\Api\Payer;
use PayPal\Api\Payment;
use PayPal\Api\PaymentExecution;
use PayPal\Api\RedirectUrls;
use PayPal\Api\Transaction;
use PayPal\Auth\OAuthTokenCredential;
use PayPal\Rest\ApiContext;
use Redirect;
use Session;
use URL;
*/

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::with('localisation')->get();
        return view('admin.pages.users.index', compact('users'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::where('name', '!=', 'patient')->get();
        $types = TypeDoctor::all();
        $locales = Localisation::all();
        $user = new User();
        return view('admin.pages.users.create', compact('locales', 'roles', 'user', 'types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make(
            $request->all(),
            [
                'name' => ['required', 'string', 'max:255'],
                'surname' => ['required', 'string', 'max:255','nullable'],
                'contact' => ['required', 'string', 'max:255'],
                'patients' => ['required', 'sometimes'],
                'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
                'password' => ['required', 'string', 'min:8', 'confirmed'],
            ]
        )->validate();

        $nurse_id = $request->nurses;

        if($nurse_id == 0 && $request->role == "medecin" && empty($request->patients))
        {
            /* if(empty($request->patients))
            return back()->with('error', 'veuillez rajouter aux moins un patient'); */
            /* Validator::make(
                $request->all(),
                [
                    'namef' => ['required', 'string', 'max:255'],
                    'surnamef' => ['required', 'max:255', 'string', 'nullable'],
                    'contactf' => ['required', 'max:255', 'string'],
                    'emailf' => ['required', 'email', 'max:255'],
                    'passwordf' => ['required', 'string', 'min:8', 'required_with:password_confirmationf', 'same:password_confirmationf'],
                    'password_confirmationf' => ['min:8']
                ]
            )->validate(); */

            try{

                DB::beginTransaction();

                // creation du medecin
                $doctor = User::create(["name" => $request->name, 'email' => $request->email, 'password' =>$request->password,
                "surname" => $request->surname,"contact" => $request->contact,"localisation_id" => $request->zone,
                 "role" => $request->role, "type_doctor_id" => $request->type, 'email_verified_at' => now() ]);

                // liaison du medecin aux patients
                /* foreach($request->patients as $el){
                    $patient = \App\Models\User::findOrFail($el);
                    $patient->user_id = $doctor->id;
                    $patient->busy = true;
                    $patient->save();
                } */
               
                
                // creation de  l'infirmier
                /*$nurse = User::create(["name" => $request->namef, 'email' => $request->emailf, 'password' => Hash::make($request->passwordf),
                "surname" => $request->surnamef,"contact" => $request->contactf,"localisation_id" => $request->zone,
                 "role" => "infirmier", "user_id" => $doctor->id, 'email_verified_at' => now() ]);*/

                // attribution du role
                /* $role = Role::where('name', $request->role)->first();
                $doctor->assignRole([$role->id]); */

                // attribution du role
               /*  $role = Role::where('name', 'infirmier')->first();
                $nurse->assignRole([$role->id]); */

                // envoi de mail audoctoeur et à l'infirmier
                
                Mail::to($doctor->email)->queue(new UserMail($doctor));
                $doctor->password = Hash::make($request->password);
                $doctor->save();
                
               // Mail::to($nurse->email)->queue(new UserMail($nurse));

                DB::commit();

            }catch (\PDOException $e) {
                return $e->getMessage();
                DB::rollBack();
            } 

            return redirect()->route('users.index')->with('store');
           
        }

        if($nurse_id != 0 && $request->role == "medecin"  && empty($request->patients))
        {
            try{
                  DB::beginTransaction();

                    $doctor = User::create(["name" => $request->name, 'email' => $request->email, 'password' => $request->password,
                    "surname" => $request->surname,"contact" => $request->contact,"localisation_id" => $request->zone,
                    "role" => $request->role, "type_doctor_id" => $request->type, 'email_verified_at' => now() ]); 
                
                    // liaison du medecin à l'infirmier
                    $nurse = User::where('id', $request->nurses)->first();
                    $nurse->user_id = $doctor->id;
                    $nurse->save();

                    // attribution du role et envoi du mail
                    $role = Role::where('name', $request->role)->first();
                    $doctor->assignRole($role->id);
                    
                    Mail::to($doctor->email)->queue(new UserMail($doctor));

                    $doctor->password = Hash::make($request->password);
                    $doctor->save();
                  DB::commit();

                }catch (\PDOException $e) {
                    return $e->getMessage();
                    DB::rollBack();
                }
            
                return redirect()->route('users.index')->with('store');
        }

        if($nurse_id != 0 && $request->role == "medecin"  && !empty($request->patients))
        {
            try{
                  DB::beginTransaction();

                     $doctor = User::create(["name" => $request->name, 'email' => $request->email, 'password' => $request->password,
                     "surname" => $request->surname,"contact" => $request->contact,"localisation_id" => $request->zone,
                      "role" => $request->role, "type_doctor_id" => $request->type, 'email_verified_at' => now() ]); 
                 
                    // liaison du medecin à l'infirmier
                    $nurse = User::where('id', $request->nurses)->first();
                    $nurse->user_id = $doctor->id;
                    $nurse->save();

                    // liaison du medecin aux patients
                    foreach($request->patients as $el){
                        $patient = \App\Models\User::findOrFail($el);
                        $patient->user_id = $doctor->id;
                        $patient->busy = true;
                        $patient->save();
                    } 

                     // attribution du role et envoi du mail
                     $role = Role::where('name', $request->role)->first();
                     $doctor->assignRole($role->id);
                     
                     Mail::to($doctor->email)->queue(new UserMail($doctor));
                     $doctor->password = Hash::make($request->password);
                     $doctor->save();
                  DB::commit();

                }catch (\PDOException $e) {
                    return $e->getMessage();
                    DB::rollBack();
                }
            
                return redirect()->route('users.index')->with('store');
        }

        if($nurse_id == 0 && $request->role == "medecin" && !empty($request->patients))
        {
           
            try{

                DB::beginTransaction();

                // creation du medecin
                $doctor = User::create(["name" => $request->name, 'email' => $request->email, 'password' => $request->password,
                "surname" => $request->surname,"contact" => $request->contact,"localisation_id" => $request->zone,
                 "role" => $request->role, "type_doctor_id" => $request->type, 'email_verified_at' => now() ]);

                // liaison du medecin aux patients
                foreach($request->patients as $el){
                    $patient = \App\Models\User::findOrFail($el);
                    $patient->user_id = $doctor->id;
                    $patient->busy = true;
                    $patient->save();
                } 

                // envoi de mail audoctoeur et à l'infirmier
                
                Mail::to($doctor->email)->queue(new UserMail($doctor));
                $doctor->password = Hash::make($request->password);
                $doctor->save();

                DB::commit();

            }catch (\PDOException $e) {
                return $e->getMessage();
                DB::rollBack();
            } 

            return redirect()->route('users.index')->with('store');
           
        }


        if($request->role == "user")
        {
            try{
                DB::beginTransaction();

resources/views/admin/pages/users/patients/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Administration Dashboard-Patients_list')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1 class="text-uppercase">Liste des patients</h1>
                <input type="hidden" id="jitsi-name" value="{{ auth()->user()->name }}" />
          	    <input type="hidden" id="jitsi-email" value="{{ auth()->user()->email }}" />
            </div>

            <div class="section-body">
                <div class="section-body">
                <div class="row">
                <div class="col-12">
                    <div class="card">
                   
                    <div class="card-body">
                        <div class="table-responsive">
                        <table class="table table-striped" id="table-1">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Noms et Prenoms</th>
                                <th>Email</th>
                                <th>Role</th>
                                <th>Zone</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($users as $user)
                                <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $user->name }} {{ $user->surname }}</td>
                                <td>{{ $user->email }}</td>
                                <td>{{ $user->role }}</td>
                                <td>{{ $user->localisation ? $user->localisation->name : '' }}</td>
                                <td>
                                    <a class="btn btn-info btn-action mr-1" href="{{ route('users.show', $user)  }}" data-toggle="tooltip" title="" data-original-title="Details">
                                    <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="btn btn-info btn-action mr-1" href="{{ route('users.medical.users', $user)  }}" data-toggle="tooltip" title="" data-original-title="Dossier medical">
                                    <i class="fas fa-book-open"></i>
                                    </a>
                                    <a class="btn btn-info btn-action mr-1 meet" href="#" data-toggle="tooltip" title="" data-original-title="Contacter">
                                    <i class="fas fa-phone-volume"></i>
                                    </a>
                                    {{--<a class="btn btn-info btn-action mr-1"  href="#" data-toggle="tooltip" title="" data-original-title="Fermer Jitsi" style="display:none">
                                    <i class="fas fa-times-circle"></i>
                                    </a>--}}
                                   
                                    {{--<a class="btn btn-danger btn-action trigger--fire-modal-1" 
                                    data-toggle="tooltip" title="" 
                                    data-confirm="Are You Sure?|This action can not be undone. Do you want to continue?" 
                                    data-confirm-yes="alert('Deleted')" data-original-title="Delete">
                                    <i class="fas fa-trash"></i>
                                    </a>--}}
                                   
                                </td>
                                </tr>
                            @empty
                            @endforelse
                            </tbody>
                        </table>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
                </div>
            <div class="row" style="display:none" id="container-jitsi">
                <div class="col-sm-10 offset-sm-1">
                    <button type="button" class="btn btn-primary btn-lg btn-block" id="close-jitsi">Fermer Jitsi</button>
                </div>
          	</div>
            <div class="row mt-3">
                 <div class="col-sm-8 offset-sm-2">
                     <div id="jitsi-meet"></div>
                 </div>
          	</div>
        </section>
    </div>
@endsection

@section('scripts')

    <script src='https://meet.jit.si/external_api.js'></script>
    <script type="text/javascript">
        $(function(){
            
            $('.meet').each(function(){
                
                $(this).on('click', function(){
               
                    $('#container-jitsi').css('display','')
     
                    const domain = 'meet.jit.si';
                    const options = {
                        configOverwrite: { startWithAudioMuted: false },
                        userInfo: {
                            email: $('#jitsi-email').val(),
                            displayName: $('#jitsi-name').val()
                        },
                        roomName: 'Prise Rendez-vous',
                        width: 700,
                        height: 700,
                        parentNode: document.querySelector('#jitsi-meet')
                    };
                    const api = new JitsiMeetExternalAPI(domain, options);
                    //api.executeCommand('toggleAudio');
                    
                    $('#close-jitsi').click(function(){
                        $('#jitsi-meet').empty()
                        $(this).parent().parent().css('display', 'none')
                    })
                })
           
           })
            
           
        })
    </script>
   
@endsection