routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.pages.auth.login');
})->name('admin.login');

Route::get('/send-email', function (Request $request) {
    return view('admin.pages.auth.send_email');
})->name('admin.send_email');

Route::get('/inscription', function () {
    return view('admin.pages.auth.register');
})->name('inscription');

Route::get('/confirm', function () {
    return view('admin.pages.auth.confirm');
})->name('confirm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'], 'prefix' => 'accueil'], function () {
   
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('locales', 'LocalisationController')->except(['show']);
    Route::resource('roles', 'RoleController')->except(['show']);
    Route::resource('type-rdvs', 'TypeRdvController')->except(['show']);
    Route::resource('antecedents', 'AntecedentController')->except(['show']);
    Route::resource('type-antecedents', 'TypeAntecedentController')->except(['show']);
    Route::resource('type-doctors', 'TypeDoctorController')->except(['show']);
    Route::resource('type-soins', 'TypeSoinController')->except(['show']);
    Route::resource('type-interventions', 'TypeInterventionController')->except(['show']);
    Route::post('users/password', 'UserController@password')->name('users.password');
    Route::get('users/password', 'UserController@getPassword')->name('users.password');
    Route::get('users/role', 'UserController@role');
    Route::put('users/profile', 'UserController@profile')->name('users.profile.update');
    Route::get('users/profile', 'UserController@getprofile')->name('users.profile');
    Route::get('users/zone/{id}/{role}', 'UserController@getUsersByZone')->name('users.zone');
    Route::get('users/listing/{type}', 'UserController@listing')->name('users.listing');
    Route::delete('users/delete/{id}', 'UserController@delete')->name('users.delete');
    Route::get('users/medical', 'UserController@dossierMedical')->name('users.medical');
    Route::get('users/medical/users/{id}', 'UserController@dossierMedicalBis')->name('users.medical.users'); 
    Route::get('users/nurses/index', 'UserController@nursePatient')->name('users.nurses.index');
    Route::get('users/nurses/create', 'UserController@createPatient')->name('users.nurses.create');
    Route::get('users/doctor/patient', 'UserController@doctorPatient')->name('users.doctor.patient');
    Route::get('users/forfait', 'UserController@userForfait')->name('users.forfait');
    Route::post('users/forfait/store', 'UserController@forfait')->name('users.forfait.store');
    Route::post('users/nurses/store', 'UserController@nurseStore')->name('users.nurses.store');
    Route::get('users/assign/patients', 'UserController@getAssignForm')->name('users.assign');
    Route::get('users/assign/{id}', 'UserController@assignFind')->name('users.assign.find');
    Route::post('users/assign/patients', 'UserController@assignPatientToDoctor')->name('users.assign.store');
    Route::resource('users', 'UserController');
    Route::get('intervention/nurse/', 'RdvController@interventionNonNurse')->name('interventions.nurse');
    Route::get('intervention/doctor/', 'RdvController@doctorInvalidRdv')->name('interventions.doctor');
    Route::get('rdvs/patient', 'RdvController@patientRdv')->name('rdvs.patient');
    Route::get('rdvs/doctor', 'RdvController@doctorRdv')->name('rdvs.doctors');
    Route::get('rdvs/nurse', 'RdvController@nurseRdv')->name('rdvs.nurses');
    Route::get('rdvs/nurse/invalid', 'RdvController@nurseInvalidRdv')->name('rdvs.nurses.invalid');
    Route::get('rdvs/confirm/{id}', 'RdvController@confirm');
    Route::resource('rdvs', 'RdvController');
    Route::get('soins/details/{id}', 'SoinController@details')->name('soins.details');
    Route::resource('soins', 'SoinController');
    Route::get('forfaits/details/{id}', 'ForfaitController@detailsForfait');
    Route::resource('forfaits', 'ForfaitController');
    Route::resource('services', 'ServiceController');

    // Route qui affiche les interventions non effectuées par un medecin
    Route::get('interventions/medecin/{id}', 'InterventionController@interventionsNonEffectueesParMedecin')->name('interventions.medecin');
    // Route qui affiche les interventions non effectuées par l'infirmière
    Route::get('interventions/infirmiere/{id}', 'InterventionController@interventionsNonEffectueesParInfirmiere')->name('interventions.infirmiere');
    // Route qui affiche les rendez-vous pour un patient
    //Route::get('rdvs/patient/{id}', 'RdvController@patientRDV')->name('rdvs.patient');

});

resources/views/admin/layouts/partials/footer.blade.php
<footer class="main-footer">
    <div class="footer-left">
        Copyright &copy; {{ date('Y') }} <div class="bullet"></div> Design By <a href="https://dw-digital.dreamwpro.com/">DreamWPro</a>
    </div>
    <div class="footer-right"></div>
</footer>

resources/views/admin/layouts/partials/include.blade.php
@push('base_link')
    <!-- General CSS Files -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{{ asset('assets/admin/css/switchery.css') }}"></script>

  <!-- Template CSS -->
  <link rel="stylesheet" href="{{ asset('assets/admin/css/style.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/admin/css/components.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/admin/css/custom.css') }}">

  <!-- Datatable css -->
  <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
  <!-- iziToast css -->
  <link rel="stylesheet" href="{{ asset('assets/admin/css/iziToast.min.css') }}">
  <link rel="stylesheet" href="{{ asset('assets/admin/css/select2.min.css') }}">
  
@endpush
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
@push('base_script')
    <!-- General JS Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src=" {{ asset('assets/admin/js/stisla.js') }}"></script>

    <!-- JS Libraies -->
    <script src="{{ asset('js/Xhttp_ActiveX.js') }}"></script>
    <script src="{{ asset('assets/admin/js/switchery.js') }}"></script>

    <!-- Template JS File -->
    <script src="{{ asset('assets/admin/js/scripts.js') }}"></script>
    <script src="{{ asset('assets/admin/js/custom.js') }}"></script>
    
    <!-- Page Datatable JS File -->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('assets/admin/js/page/modules-datatables.js') }}"></script>
    <!-- iziToast js -->
    <script src="{{ asset('assets/admin/js/iziToast.min.js') }}"></script>
    <script src="{{ asset('/assets/admin/js/select2.min.js') }}"></script>
    <script>
      @if(session('store'))
        iziToast.success({
          title: 'Creation du {{ session('store') }}',
          message: '{{ session('store') }} Créé avec succès',
          position: 'topRight'
        });
      @endif
      @if(session('delete'))
        iziToast.warning({
          title: 'Suppression du {{ session('delete') }}',
          message: '{{ session('delete') }} Supprimé avec succès',
          position: 'topRight'
        });
      @endif
      @if(session('update'))
        iziToast.info({
          title: 'Modification  de {{ session('update') }}',
          message: '{{ session('update') }} Modifié avec succès',
          position: 'topRight'
        });
      @endif
    </script>
   
@endpush

resources/views/admin/layouts/partials/navbar.blade.php
<div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar">
        <form class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
          </ul>
          <!--
          <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
            <div class="search-backdrop"></div>
            <div class="search-result">
              <div class="search-header">
                Histories
              </div>
              <div class="search-item">
                <a href="#">How to hack NASA using CSS</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-item">
                <a href="#">Kodinger.com</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-item">
                <a href="#">#Stisla</a>
                <a href="#" class="search-close"><i class="fas fa-times"></i></a>
              </div>
              <div class="search-header">
                Result
              </div>
              <div class="search-item">
                <a href="#">
                  <img class="mr-3 rounded" width="30" src="{{ asset('assets/admin/img/products/product-3-50.png') }}" alt="product">
                  oPhone S9 Limited Edition
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <img class="mr-3 rounded" width="30" src="{{ asset('assets/admin/img/products/product-2-50.png') }}" alt="product">
                  Drone X2 New Gen-7
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <img class="mr-3 rounded" width="30" src="{{ asset('assets/admin/img/products/product-1-50.png') }}" alt="product">
                  Headphone Blitz
                </a>
              </div>
              <div class="search-header">
                Projects
              </div>
              <div class="search-item">
                <a href="#">
                  <div class="search-icon bg-danger text-white mr-3">
                    <i class="fas fa-code"></i>
                  </div>
                  Stisla Admin Template
                </a>
              </div>
              <div class="search-item">
                <a href="#">
                  <div class="search-icon bg-primary text-white mr-3">
                    <i class="fas fa-laptop"></i>
                  </div>
                  Create a new Homepage Design
                </a>
              </div>
            </div>
          </div>
          -->
        </form>
        <ul class="navbar-nav navbar-right">
          <!--
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Messages
                <div class="float-right">
                  <a href="#">Mark All As Read</a>
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-message">
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-1.png') }}" class="rounded-circle">
                    <div class="is-online"></div>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Kusnaedi</b>
                    <p>Hello, Bro!</p>
                    <div class="time">10 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-2.png') }}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Dedik Sugiharto</b>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-3.png') }}" class="rounded-circle">
                    <div class="is-online"></div>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Agung Ardiansyah</b>
                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-4.png') }}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Ardian Rahardiansyah</b>
                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                    <div class="time">16 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-avatar">
                    <img alt="image" src="{{ asset('assets/admin/img/avatar/avatar-5.png') }}" class="rounded-circle">
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Alfa Zulkarnain</b>
                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                    <div class="time">Yesterday</div>
                  </div>
                </a>
              </div>
              <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Notifications
                <div class="float-right">
                  <a href="#">Mark All As Read</a>
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
                <a href="#" class="dropdown-item dropdown-item-unread">
                  <div class="dropdown-item-icon bg-primary text-white">
                    <i class="fas fa-code"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    Template update is available now!
                    <div class="time text-primary">2 Min Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-info text-white">
                    <i class="far fa-user"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                    <div class="time">10 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-success text-white">
                    <i class="fas fa-check"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                    <div class="time">12 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-danger text-white">
                    <i class="fas fa-exclamation-triangle"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    Low disk space. Let's clean it!
                    <div class="time">17 Hours Ago</div>
                  </div>
                </a>
                <a href="#" class="dropdown-item">
                  <div class="dropdown-item-icon bg-info text-white">
                    <i class="fas fa-bell"></i>
                  </div>
                  <div class="dropdown-item-desc">
                    Welcome to Stisla template!
                    <div class="time">Yesterday</div>
                  </div>
                </a>
              </div>
              <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          -->
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
            @if(auth()->user()->profile))
              <img alt="image" src="{{ asset('public/assets/admin/uploads/'.auth()->user()->profile) }}" class="rounded-circle mr-1">
            @else
             <img alt="image" src="{{ asset('public/assets/admin/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
            @endif

            <div class="d-sm-none d-lg-inline-block">{{auth()->user()->name}}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <!--<div class="dropdown-title">Logged in 5 min ago</div>-->
              <a href="#" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Profil
              </a>
              <!--
              <a href="features-activities.html" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Activities
              </a>
              <a href="features-settings.html" class="dropdown-item has-icon">
                <i class="fas fa-cog"></i> Settings
              </a>
              -->
              <div class="dropdown-divider"></div>
              <a href="{{ route('logout') }}" class="dropdown-item has-icon text-danger" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                  <i class="fas fa-sign-out-alt"></i> Logout
              </a>
              <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                  {{ csrf_field() }}
              </form>
            </div>
          </li>
        </ul>
      </nav>

resources/views/admin/layouts/partials/sidebar.blade.php
<div class="main-sidebar">
        <aside id="sidebar-wrapper">
          <div class="sidebar-brand">
            <a href="{{ url('/') }}">Benss</a>
          </div>
          <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">Bs</a>
          </div>
          

          <ul class="sidebar-menu">
            @if(auth()->user()->role == 'admin')
              <li class="menu-header">Manager</li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-users"></i><span>Utilisateurs</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('users.create') }}">Creation</a></li>
                  <li><a class="nav-link" href="{{ route('users.index') }}">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('users.listing', 'patient') }}">Listing Patients</a></li>
                  <li><a class="nav-link" href="{{ route('users.listing', 'medecin') }}">Listing Medecins</a></li>
                  <li><a href="{{ route('users.assign') }}" class="nav-link">Attribuer Patients</a></li>
                  <li><a class="nav-link" href="{{ route('users.listing', 'infirmier') }}">Listing Infirmiers</a></li>                  
                </ul>
              </li>
              
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-map-marked-alt"></i><span>Zones</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('locales.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('locales.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-user-md"></i><span>Types de médecins</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('type-doctors.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('type-doctors.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-stethoscope"></i><span>Types de Soins</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('type-soins.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('type-soins.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Types de Rdv</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('type-rdvs.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('type-rdvs.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Types d'interventions</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('type-interventions.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('type-interventions.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Services</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('services.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('services.create') }}">Creation</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Forfaits</span></a>
                <ul class="dropdown-menu">
                  <li><a class="nav-link" href="{{ route('forfaits.index') }} ">Listing</a></li>
                  <li><a class="nav-link" href="{{ route('forfaits.create') }}">Creation</a></li>
                </ul>
              </li>
              
              

            @endif

            @if(auth()->user()->role == 'patient')
            
                @if(auth()->user()->user_id != NULL && auth()->user()->forfait_id != NULL)
                    <li class="nav-item dropdown">
                      <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>RDVs</span></a>
                      <ul class="dropdown-menu">
                        <li><a class="nav-link" href="{{ route('rdvs.patient') }}">listing</a></li>
                        <li><a class="nav-link" href="{{ route('rdvs.create') }}">create</a></li>
                        <li><a class="nav-link" href="#" id="meet">contacter son medecin</a></li>
                      </ul>
                    </li>
                @endif

                <li class="nav-item dropdown">
                      <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Antecedents</span></a>
                      <ul class="dropdown-menu">
                        <li><a class="nav-link" href="{{ route('antecedents.index') }}">listing</a></li>
                        <li><a class="nav-link" href="{{ route('antecedents.create') }}">create</a></li>
                      </ul>
                </li>

              <li class="menu-header">Compte</li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.profile') }}" class="nav-link"><i class="fas fa-book"></i> <span>Profile</span></a>
              </li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.password') }}" class="nav-link"><i class="fas fa-book"></i> <span>Changer votre password</span></a>
              </li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.medical') }}" class="nav-link"><i class="fas fa-book"></i> <span>Dossier medical</span></a>
              </li>
              @if(auth()->user()->forfait_id == NULL)
                <li class="nav-item dropdown">
                  <a href="{{ route('users.forfait') }}" class="nav-link"><i class="fas fa-book"></i> <span>Forfait</span></a>
                </li>
              @endif
            @endif

            @if(auth()->user()->role == 'medecin')

              <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Patients</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('users.doctor.patient') }}">listing</a></li>
                  </ul>
              </li>

              <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Interventions</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('rdvs.doctors') }}">listing</a></li>
                  </ul>
              </li>

              <li class="menu-header">Compte</li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.profile') }}" class="nav-link"><i class="fas fa-book"></i> <span>Profil</span></a>
              </li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.password') }}" class="nav-link"><i class="fas fa-book"></i> <span>Changer votre password</span></a>
              </li>
            @endif

            @if(auth()->user()->role == 'infirmier')

              <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>Patients</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('users.nurses.index') }}">listing</a></li>
                    <li><a class="nav-link" href="{{ route('users.nurses.create') }}">create</a></li>
                  </ul>
              </li>
              <li class="nav-item dropdown">
                  <a href="#" class="nav-link has-dropdown"><i class="far fa-calendar-check"></i><span>RDV</span></a>
                  <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{ route('rdvs.nurses') }}">listing</a></li>
                  </ul>
              </li>

        

              <li class="menu-header">Compte</li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.profile') }}" class="nav-link"><i class="fas fa-book"></i> <span>Profile</span></a>
              </li>
              <li class="nav-item dropdown">
                <a href="{{ route('users.password') }}" class="nav-link"><i class="fas fa-book"></i> <span>Changer votre password</span></a>
              </li>
            @endif

           

            </ul>

           <!--  <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
              <a href="https://getstisla.com/docs" class="btn btn-primary btn-lg btn-block btn-icon-split">
                <i class="fas fa-rocket"></i> Documentation
              </a>
            </div> -->
          
        </aside>
      </div>