routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.pages.auth.login');
})->name('admin.login');

Route::get('/send-email', function (Request $request) {
    return view('admin.pages.auth.send_email');
})->name('admin.send_email');

Route::get('/inscription', function () {
    return view('admin.pages.auth.register');
})->name('inscription');

Route::get('/confirm', function () {
    return view('admin.pages.auth.confirm');
})->name('confirm');

Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'], 'prefix' => 'accueil'], function () {
   
    Route::get('/', 'HomeController@index')->name('home');
    Route::resource('locales', 'LocalisationController')->except(['show']);
    Route::resource('roles', 'RoleController')->except(['show']);
    Route::resource('type-rdvs', 'TypeRdvController')->except(['show']);
    Route::resource('antecedents', 'AntecedentController')->except(['show']);
    Route::resource('type-antecedents', 'TypeAntecedentController')->except(['show']);
    Route::resource('type-doctors', 'TypeDoctorController')->except(['show']);
    Route::resource('type-soins', 'TypeSoinController')->except(['show']);
    Route::resource('type-interventions', 'TypeInterventionController')->except(['show']);
    Route::post('users/password', 'UserController@password')->name('users.password');
    Route::get('users/password', 'UserController@getPassword')->name('users.password');
    Route::get('users/role', 'UserController@role');
    Route::put('users/profile', 'UserController@profile')->name('users.profile.update');
    Route::get('users/profile', 'UserController@getprofile')->name('users.profile');
    Route::get('users/zone/{id}/{role}', 'UserController@getUsersByZone')->name('users.zone');
    Route::get('users/listing/{type}', 'UserController@listing')->name('users.listing');
    Route::delete('users/delete/{id}', 'UserController@delete')->name('users.delete');
    Route::get('users/medical', 'UserController@dossierMedical')->name('users.medical');
    Route::get('users/medical/users/{id}', 'UserController@dossierMedicalBis')->name('users.medical.users'); 
    Route::get('users/nurses/index', 'UserController@nursePatient')->name('users.nurses.index');
    Route::get('users/nurses/create', 'UserController@createPatient')->name('users.nurses.create');
    Route::get('users/doctor/patient', 'UserController@doctorPatient')->name('users.doctor.patient');
    Route::get('users/forfait', 'UserController@userForfait')->name('users.forfait');
    Route::post('users/forfait/store', 'UserController@forfait')->name('users.forfait.store');
    Route::post('users/nurses/store', 'UserController@nurseStore')->name('users.nurses.store');
    Route::get('users/assign/patients', 'UserController@getAssignForm')->name('users.assign');
    Route::get('users/assign/{id}', 'UserController@assignFind')->name('users.assign.find');
    Route::post('users/assign/patients', 'UserController@assignPatientToDoctor')->name('users.assign.store');
    Route::resource('users', 'UserController');
    Route::get('intervention/nurse/', 'RdvController@interventionNonNurse')->name('interventions.nurse');
    Route::get('intervention/doctor/', 'RdvController@doctorInvalidRdv')->name('interventions.doctor');
    Route::get('rdvs/patient', 'RdvController@patientRdv')->name('rdvs.patient');
    Route::get('rdvs/doctor', 'RdvController@doctorRdv')->name('rdvs.doctors');
    Route::get('rdvs/nurse', 'RdvController@nurseRdv')->name('rdvs.nurses');
    Route::get('rdvs/nurse/invalid', 'RdvController@nurseInvalidRdv')->name('rdvs.nurses.invalid');
    Route::get('rdvs/confirm/{id}', 'RdvController@confirm');
    Route::resource('rdvs', 'RdvController');
    Route::get('soins/details/{id}', 'SoinController@details')->name('soins.details');
    Route::resource('soins', 'SoinController');
    Route::get('forfaits/details/{id}', 'ForfaitController@detailsForfait');
    Route::resource('forfaits', 'ForfaitController');
    Route::resource('services', 'ServiceController');

    // Route qui affiche les interventions non effectuées par un medecin
    Route::get('interventions/medecin/{id}', 'InterventionController@interventionsNonEffectueesParMedecin')->name('interventions.medecin');
    // Route qui affiche les interventions non effectuées par l'infirmière
    Route::get('interventions/infirmiere/{id}', 'InterventionController@interventionsNonEffectueesParInfirmiere')->name('interventions.infirmiere');
    // Route qui affiche les rendez-vous pour un patient
    //Route::get('rdvs/patient/{id}', 'RdvController@patientRDV')->name('rdvs.patient');

});

app/Models/TypeIntervention.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class TypeIntervention extends Model
{
    public $timestamps = false;
    protected $fillable = [
        'name',
    ];
}

app/Http/Controllers/TypeInterventionController.php
<?php

namespace App\Http\Controllers;

use App\Models\TypeIntervention;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;

class TypeInterventionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $types = TypeIntervention::all();
        return view('admin.pages.type_interventions.index', compact('types'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $type = new TypeIntervention();
        return view('admin.pages.type_interventions.create', compact('type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make(
            $request->all(),
            [
                'name' => ['required', 'string', 'max:255', 'unique:type_interventions'],
            ]
        )->validate();

        $type = TypeIntervention::create(["name" => $request->name]);
        return redirect()->route('type-interventions.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\TypeIntervention  $tYpeIntervention
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\TypeIntervention  $tYpeIntervention
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $type = TypeIntervention::findOrFail($id);
        return view('admin.pages.type_interventions.edit', compact('type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\TypeIntervention  $tYpeIntervention
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $type = TypeIntervention::findOrFail($id);
        Validator::make(
            $request->all(),
            [
                'name' => ['required', 'string', 'max:255', 'unique:type_interventions'],
            ]
        )->validate();

        $type->update(["name" => $request->name]);
        return redirect()->route('type-interventions.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\TypeIntervention  $tYpeIntervention
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $type = TypeIntervention::findOrFail($id);
        $type->delete();
        return redirect()->route('type-interventions.index');
    }
}

resources/views/admin/pages/type_interventions/create.blade.php
@extends('admin.layouts.app')
@section('title', 'Administration Dashboard-Interventions_list')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1 class="text-uppercase">Ajouter une intervention</h1>
            </div>

            <div class="section-body">
               @include('admin.pages.type_interventions.form')
            </div>
        </section>
    </div>
@endsection

resources/views/admin/pages/type_interventions/edit.blade.php
@extends('admin.layouts.app')
@section('title', 'Administration Dashboard-Intervention_list')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1 class="text-uppercase">Modifier une intervention</h1>
            </div>

            <div class="section-body">
               @include('admin.pages.type_interventions.form')
            </div>
        </section>
    </div>
@endsection

resources/views/admin/pages/type_interventions/form.blade.php
<?php
if ($type->id) {
    $options = ['method' => 'put', 'url' => route('type-interventions.update',$type)];
} else {
    $options = ['method' => 'post', 'url' => route('type-interventions.store')];
}
?>
@include('utilities.errors')
@include('utilities.flash')

{!! Form::model($type, $options,['class'=>'','enctype'=>"multipart/form-data",'accept-charset'=>"utf-8"]) !!}
@csrf

<div class="card">
    <div class="card-body">
        <div class="form-group">
            {!! Form::label('name', 'Nom de l\'intervention') !!}
            {!! Form::text('name', null , ['class' => 'form-control', 'required'=>'required', 'placeholder'=>"Nom de l'intervention"]) !!}
        </div>
        <div class="card">
            <div class="card-footer text-right">
                <button class="btn btn-secondary" type="reset">Reset</button>
                <button class="btn btn-primary" type="submit">Validé</button>
            </div>
        </div>
    </div>
</div>
{!! Form::close() !!} 

resources/views/admin/pages/type_interventions/index.blade.php
@extends('admin.layouts.app')
@section('title', 'Administration Dashboard-Interventions_list')
@section('content')
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1 class="text-uppercase">Types d'interventions</h1>
            </div>

            <div class="section-body">
                <div class="section-body">
                <div class="row">
                <div class="col-12">
                    <div class="card">
                    <div class="card-header">
                        <a href="{{ route('type-interventions.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Nouveau</a>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                        <table class="table table-striped" id="table-1">
                            <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($types as $type)
                                <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $type->name }}</td>
                                <td>
                                    <a class="btn btn-info btn-action mr-1" href="#" data-toggle="tooltip" title="" data-original-title="Show">
                                    <i class="fas fa-eye"></i>
                                    </a>
                                    <a class="btn btn-primary btn-action mr-1" href="{{ route('type-interventions.edit', $type) }}" data-toggle="tooltip" title="" data-original-title="Edit">
                                    <i class="fas fa-pencil-alt"></i>
                                    </a>
                                    {{--<a class="btn btn-danger btn-action trigger--fire-modal-1" 
                                    data-toggle="tooltip" title="" 
                                    data-confirm="Are You Sure?|This action can not be undone. Do you want to continue?" 
                                    data-confirm-yes="alert('Deleted')" data-original-title="Delete">
                                    <i class="fas fa-trash"></i>
                                    </a>--}}
                                    {!! Form::open([
                                        'method'=>'DELETE',
                                        'url' => route('type-interventions.destroy', $type),
                                        'style' => 'display:inline'
                                    ]) !!}
                                    {!! Form::button('<i class="fas fa-trash"></i> ', array(
                                        'type' => 'submit',
                                        'class' => 'btn btn-danger',
                                        'title' => 'Type Doctor',
                                    )) !!}
                            {!! Form::close() !!}
                                </td>
                                </tr>
                            @empty
                            @endforelse
                            </tbody>
                        </table>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
                </div>
        </section>
    </div>
@endsection